module.exports.config = {
                name: "زخرفةا",
		version: "1.3",
		author: "محمد تانجيرو",
		countDown: 5,
		role: 0,
		description: { ar: "زخرفة أي كلمة أو جملة تكتبها بالانجليزي أو الفرنسي" },
		category: "events",
		guide: { ar: "{pn} [النص]" }
			   };
module.exports.onStart = async function({ api, event, args }) {
    const { threadID, messageID, senderID, body } = event;
 var content = args.join(" ").toLowerCase();
      if (!content) return api.sendMessage("يرجى إدخال النص الذي تريد زخرفته", threadID, messageID);
    let a = content.replace(/a/g, "𝒂").replace(/ạ/g, "𝒂̣").replace(/à/g, "𝒂̀").replace(/ả/g, "𝒂̉").replace(/á/g,"𝒂́").replace(/ắ/g, "𝒂̆́").replace(/ằ/g, "𝒂̆̀").replace(/ă/g, "𝒂̆").replace(/q/g, "𝒒").replace(/w/g, "𝒘").replace(/e/g, "𝒆").replace(/ể/g, "𝒆̂̉").replace(/ế/g, "𝒆̂́").replace(/ẹ/g, "𝒆̣").replace(/ê/g, "𝒆̂").replace(/ề/g, "𝒆̂̀").replace(/r/g, "𝒓").replace(/t/g, "𝒕").replace(/ỵ/g, "𝒚̣").replace(/y/g, "𝒚").replace(/ỷ/g, "𝒚̉").replace(/ỳ/g, "𝒚̀").replace(/u/g, "𝒖").replace(/ủ/g, "𝒖̉").replace(/ù/g, "𝒖̀").replace(/ú/g, "𝒖́").replace(/ụ/g, "𝒖̣").replace(/i/g, "𝒊").replace(/í/g, "𝒊́").replace(/ì/g, "𝒊̀").replace(/ị/g, "𝒊̣").replace(/o/g, "𝒐").replace(/ỏ/g, "𝒐̉").replace(/ò/g, "𝒐̀").replace(/ó/g, "𝒐́").replace(/ô/g, "𝒐̂").replace(/ồ/g, "𝒐̂̀").replace(/ố/g, "𝒐̂́").replace(/ổ/g, "𝒐̂̉").replace(/ố/g, "𝒐̂́").replace(/p/g, "𝒑").replace(/s/g, "𝒔").replace(/d/g, "𝒅").replace(/đ/g, "đ").replace(/f/g, "𝒇").replace(/g/g, "𝒈").replace(/h/g, "𝒉").replace(/j/g, "𝒋").replace(/k/g, "𝒌").replace(/l/g, "𝒍").replace(/z/g, "𝒛").replace(/x/g, "𝒙").replace(/c/g, "𝒄").replace(/v/g, "𝒗").replace(/b/g, "𝒃").replace(/n/g, "𝒏").replace(/m/g, "𝒎");
    let b = content.replace(/a/g, "𝓐").replace(/ạ/g, "𝓐").replace(/à/g, "𝓐̀").replace(/ả/g, "𝓐").replace(/á/g,"𝓐́").replace(/ắ/g, "𝓐").replace(/ằ/g, "𝓐").replace(/ă/g, "𝓐̆").replace(/q/g, "𝓠").replace(/w/g, "𝓦").replace(/e/g, "𝓔").replace(/ể/g, "𝓔̂̉").replace(/ế/g, "𝓔̂́").replace(/ẹ/g, "𝓔").replace(/ê/g, "𝓔").replace(/ề/g, "𝓔").replace(/r/g, "𝓡").replace(/t/g, "𝓣").replace(/ỵ/g, "𝓨̣").replace(/y/g, "𝓨").replace(/ỷ/g, "𝓨̉").replace(/ỳ/g, "𝓨̀").replace(/u/g, "𝓤").replace(/ủ/g, "𝓤").replace(/ù/g, "𝓤").replace(/ú/g, "𝓤").replace(/ụ/g, "𝓤").replace(/i/g, "𝓘").replace(/í/g, "𝓘").replace(/ì/g, "𝓘").replace(/ị/g, "𝓘̣").replace(/o/g, "𝓞").replace(/ỏ/g, "𝓞").replace(/ò/g, "𝓞").replace(/ó/g, "𝓞").replace(/ô/g, "𝓞̂").replace(/ồ/g, "𝓞").replace(/ố/g, "𝓞̂́").replace(/ổ/g, "𝓞̂̉").replace(/ố/g, "𝓞").replace(/p/g, "𝓟").replace(/s/g, "𝓢").replace(/d/g, "𝓓").replace(/đ/g, "𝓓").replace(/f/g, "𝓕").replace(/g/g, "𝓖").replace(/h/g, "𝓗").replace(/j/g, "𝓙").replace(/k/g, "𝓚").replace(/l/g, "𝓛").replace(/z/g, "𝓩").replace(/x/g, "𝓧").replace(/c/g, "𝓒").replace(/v/g, "𝓥").replace(/b/g, "𝓑").replace(/n/g, "𝓝").replace(/m/g, "𝓜");
    let c = content.replace(/a/g, "𝔸").replace(/ạ/g, "𝔸").replace(/à/g, "𝔸̀").replace(/ả/g, "𝔸").replace(/á/g,"𝔸").replace(/ắ/g, "𝔸").replace(/ằ/g, "𝔸").replace(/ă/g, "𝔸̆").replace(/q/g, "ℚ").replace(/w/g, "𝕎").replace(/e/g, "𝔼").replace(/ể/g, "𝔼").replace(/ế/g, "𝔼̂́").replace(/ẹ/g, "𝔼").replace(/ê/g, "𝔼").replace(/ề/g, "𝔼").replace(/r/g, "ℝ").replace(/t/g, "𝕋").replace(/ỵ/g, "𝕐̣").replace(/y/g, "𝕐").replace(/ỷ/g, "𝕐̉").replace(/ỳ/g, "𝕐").replace(/u/g, "𝕌").replace(/ủ/g, "𝕌").replace(/ù/g, "𝕌").replace(/ú/g, "𝕌").replace(/ụ/g, "𝕌").replace(/i/g, "𝕀").replace(/í/g, "𝕀").replace(/ì/g, "𝕀").replace(/ị/g, "𝕀").replace(/o/g, "𝕆").replace(/ỏ/g, "𝕆").replace(/ò/g, "𝕆").replace(/ó/g, "𝕆").replace(/ô/g, "𝕆").replace(/ồ/g, "𝕆").replace(/ố/g, "𝕆").replace(/ổ/g, "𝕆̂̉").replace(/ố/g, "𝕆").replace(/p/g, "ℙ").replace(/s/g, "𝕊").replace(/d/g, "𝔻").replace(/đ/g, "𝔻").replace(/f/g, "𝔽").replace(/g/g, "𝔾").replace(/h/g, "ℍ").replace(/j/g, "𝕁").replace(/k/g, "𝕂").replace(/l/g, "𝕃").replace(/z/g, "ℤ").replace(/x/g, "𝕏").replace(/c/g, "ℂ").replace(/v/g, "𝕍").replace(/b/g, "𝔹").replace(/n/g, "ℕ").replace(/m/g, "𝕄");
    let d = content.replace(/a/g, "𝗔").replace(/ạ/g, "𝗔").replace(/à/g, "𝗔").replace(/ả/g, "𝗔").replace(/á/g,"𝗔").replace(/ắ/g, "𝗔").replace(/ằ/g, "𝗔").replace(/ă/g, "𝗔̆").replace(/q/g, "𝗤").replace(/w/g, "𝗪").replace(/e/g, "𝗘").replace(/ể/g, "𝗘").replace(/ế/g, "𝗘").replace(/ẹ/g, "𝗘").replace(/ê/g, "𝗘").replace(/ề/g, "𝗘").replace(/r/g, "𝗥").replace(/t/g, "𝗧").replace(/ỵ/g, "𝗬").replace(/y/g, "𝗬").replace(/ỷ/g, "𝗬").replace(/ỳ/g, "𝗬").replace(/u/g, "𝗨").replace(/ủ/g, "𝗨").replace(/ù/g, "𝗨").replace(/ú/g, "𝗨").replace(/ụ/g, "𝗨").replace(/i/g, "𝗜").replace(/í/g, "𝗜").replace(/ì/g, "𝗜").replace(/ị/g, "𝗜").replace(/o/g, "𝗢").replace(/ỏ/g, "𝗢").replace(/ò/g, "𝗢").replace(/ó/g, "𝗢").replace(/ô/g, "𝗢").replace(/ồ/g, "𝗢").replace(/ố/g, "𝗢").replace(/ổ/g, "𝗢").replace(/ố/g, "𝗢").replace(/p/g, "𝗣").replace(/s/g, "𝗦").replace(/d/g, "𝗗").replace(/đ/g, "𝗗").replace(/f/g, "𝗙").replace(/g/g, "𝗚").replace(/h/g, "𝗛").replace(/j/g, "𝗝").replace(/k/g, "𝗞").replace(/l/g, "𝗟").replace(/z/g, "𝗭").replace(/x/g, "𝗫").replace(/c/g, "𝗖").replace(/v/g, "𝗩").replace(/b/g, "𝗕").replace(/n/g, "𝗡").replace(/m/g, "𝗠")
    let e = content.replace(/a/g, "𝐚").replace(/ạ/g, "𝐚").replace(/à/g, "𝐚").replace(/ả/g, "𝐚").replace(/á/g,"𝐚").replace(/ắ/g, "𝐚").replace(/ằ/g, "𝐚").replace(/ă/g, "𝐚").replace(/q/g, "𝐪").replace(/w/g, "𝐰").replace(/e/g, "𝐞").replace(/ể/g, "𝐞").replace(/ế/g, "𝐞").replace(/ẹ/g, "𝐞").replace(/ê/g, "𝐞").replace(/ề/g, "𝐞").replace(/r/g, "𝐫").replace(/t/g, "𝐭").replace(/ỵ/g, "𝐲").replace(/y/g, "𝐲").replace(/ỷ/g, "𝐲").replace(/ỳ/g, "𝐲").replace(/u/g, "𝐮").replace(/ủ/g, "𝐮").replace(/ù/g, "𝐮").replace(/ú/g, "𝐮").replace(/ụ/g, "𝐮").replace(/i/g, "𝐢").replace(/í/g, "𝐢").replace(/ì/g, "𝐢").replace(/ị/g, "𝐢").replace(/o/g, "𝐨").replace(/ỏ/g, "𝐨").replace(/ò/g, "𝐨").replace(/ó/g, "𝐨").replace(/ô/g, "𝐨").replace(/ồ/g, "𝐨").replace(/ố/g, "𝐨").replace(/ổ/g, "𝐨").replace(/ố/g, "𝐨").replace(/p/g, "𝐩").replace(/s/g, "𝐬").replace(/d/g, "𝐝").replace(/đ/g, "𝐝").replace(/f/g, "𝐟").replace(/g/g, "𝐠").replace(/h/g, "𝐡").replace(/j/g, "𝐣").replace(/k/g, "𝐤").replace(/l/g, "𝐥").replace(/z/g, "𝐳").replace(/x/g, "𝐱").replace(/c/g, "𝐜").replace(/v/g, "𝐯").replace(/b/g, "𝐛").replace(/n/g, "𝐧").replace(/m/g, "𝐦")
    let f = content.replace(/a/g, "𝑎").replace(/ạ/g, "𝑎").replace(/à/g, "𝑎̀").replace(/ả/g, "𝑎").replace(/á/g,"𝑎").replace(/ắ/g, "𝑎").replace(/ằ/g, "𝑎").replace(/ă/g, "𝑎̆").replace(/q/g, "𝑞").replace(/w/g, "𝑤").replace(/e/g, "𝑒").replace(/ể/g, "𝑒").replace(/ế/g, "𝑒̂́").replace(/ẹ/g, "𝑒").replace(/ê/g, "𝑒").replace(/ề/g, "𝑒").replace(/r/g, "𝑟").replace(/t/g, "𝑡").replace(/ỵ/g, "𝑦̣").replace(/y/g, "𝑦").replace(/ỷ/g, "𝑦̉").replace(/ỳ/g, "𝑦").replace(/u/g, "𝑢").replace(/ủ/g, "𝑢").replace(/ù/g, "𝑢").replace(/ú/g, "𝑢").replace(/ụ/g, "𝑢").replace(/i/g, "𝑖").replace(/í/g, "𝑖").replace(/ì/g, "𝑖").replace(/ị/g, "𝑖").replace(/o/g, "𝑜").replace(/ỏ/g, "𝑜").replace(/ò/g, "𝑜").replace(/ó/g, "𝑜").replace(/ô/g, "𝑜").replace(/ồ/g, "𝑜").replace(/ố/g, "𝑜").replace(/ổ/g, "𝑜̂̉").replace(/ố/g, "𝑜").replace(/p/g, "𝑝").replace(/s/g, "𝑠").replace(/d/g, "𝑑").replace(/đ/g, "𝑑").replace(/f/g, "𝑓").replace(/g/g, "𝑔").replace(/h/g, "ℎ").replace(/j/g, "𝑗").replace(/k/g, "𝑘").replace(/l/g, "𝑙").replace(/z/g, "̂𝑧").replace(/x/g, "𝑥").replace(/c/g, "𝑐").replace(/v/g, "𝑣").replace(/b/g, "𝑏").replace(/n/g, "𝑛").replace(/m/g, "𝑚")
      
    return api.sendMessage(`${a}\n\n${b}\n\n${c}\n\n${d}\n\n${e}\n\n${f}\n\n═════◄∘∘❀∘∘►════`, threadID,messageID);
}
